kind: Pod
apiVersion: v1
metadata:
  name: pods-secet-vol-env
spec:
  containers:
  - name: my-container
    image: nginx
    envFrom:
    - secretRef:
         name: my-secret
         optional: true
