apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-05-02T14:22:25Z"
  labels:
    app: jupyter-app
  name: jupyter-svc
  namespace: jupyter
  resourceVersion: "3133"
  uid: 2f52922e-8e7d-4a30-a898-4187c5d2dc42
spec:
  clusterIP: 10.108.21.52
  clusterIPs:
  - 10.108.21.52
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30000
    port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: jupyter-pods
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
